apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/test-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
  namespace: test
spec:
  restartPolicy: Never
  volumes:
  - name: test-vol
    persistentVolumeClaim:
      claimName: test-pvc
  containers:
  - name: pv-recycler
    image: "registry.k8s.io/busybox"
    volumeMounts:
    - name: test-vol
      mountPath: /scrub
